import { gilroy_semibold, gotham, montserrat, original, poppins } from '@/lib/font';
import Image from 'next/image';

const TermsConditionsPage = () => {
    return (
        <div className={`${poppins.className} bg-white min-h-screen`}>
            {/* Hero image with responsive sizing */}
            {/* <div className='h-full md:h-screen flex flex-col gap-4 justify-center items-center text-center text-[#2E0A49] pt-48 md:pt-24 pb-24 md:pb-2'>

                <h1 className={`${original.className} text-6xl sm:text-7xl md:text-8xl lg:text-9xl font-[700] md:mb-6 `}>
                    Terms & Conditions
                </h1>
                <h6 className={`${gotham.className}  capitalize text-xl md:3xl font-medium md:px-72`}>Privacy Policy for Haatak</h6>
            </div> */}
            {/* <div className="relative w-full h-[250px] sm:h-[350px] md:h-[450px] lg:h-[550px] rounded-2xl overflow-hidden mt-16 md:mt-24 lg:mt-36">
                <Image
                    src="/blog_imgs/terms-conditions.jpg"
                    alt="Terms & Conditions"
                    fill
                    className="object-cover"
                    sizes="(max-width: 768px) 100vw, 80vw"
                    priority
                />
            </div> */}

            <div className="container mx-auto px-4 py-8 max-w-4xl">
                <article className="prose max-w-none">
                    <section className="mb-8 md:mb-12">
                        {/* Policy title with responsive sizing */}
                        {/* <h1 className={`${gilroy_semibold.className} text-2xl sm:text-3xl md:text-4xl lg:text-5xl text-[#2E0A49] mb-4 md:mb-6 border-l-4 border-[#E39A35] pl-3 md:pl-4`}>
                            Terms & Conditions
                        </h1> */}
                        <div className='h-full md:h-screen flex flex-col gap-4 justify-center items-center text-center text-[#2E0A49] pt-48 md:pt-24 pb-24 md:pb-2'>
                        
                                        <h1 className={`${original.className} text-6xl sm:text-7xl md:text-8xl lg:text-9xl font-[700] md:mb-6 `}>
                                            Terms & Conditions
                                        </h1>
                                        <h6 className={`${gotham.className}  capitalize text-xl md:3xl font-medium md:px-72`}>Terms of Use for Haatak</h6>
                                    </div>

                        {/* Publication date */}
                        {/* <div className={`${montserrat.className} text-sm sm:text-base md:text-lg py-3 md:py-4 text-[#2E0A49]`}>
                            Terms of Use for Haatak
                        </div> */}

                        {/* Terms content with responsive text sizing */}
                        <div className="text-base md:text-lg space-y-6">
                            {/* <h2 className={`${gilroy_semibold.className} text-xl md:text-2xl text-[#2E0A49] mt-6 mb-3`}>
                                Terms of Use for Haatak
                            </h2> */}

                            <p>
                                Welcome to Haatak! We are Unibridg Assets and Vault Private Limited., located at 455 D, 1st Floor, Eshaan Arcade, REMCO BHEL Layout, Rajarajeshwari Nagar, Bengaluru - 560098. We are committed to providing a clear and fair experience on our platform. Your trust and satisfaction are important to us, and we strive to ensure that our services meet your expectations.
                            </p>

                            <p>
                                This document outlines the terms and conditions for using our website, WAP site, or mobile applications. By using our services, you agree to these terms. If you do not agree, please do not use our platform. Please note that these terms may be updated periodically, so we recommend checking this document regularly for any changes.
                            </p>

                            {/* Section 1: Introduction */}
                            <div className="  pl-4">
                                <h3 className={`${gilroy_semibold.className} text-lg md:text-xl text-[#2E0A49] mt-6 mb-2`}>
                                    1. Introduction
                                </h3>

                                <ol className="list-decimal pl-5 space-y-3">
                                    <li>
                                        <p>This document is an electronic record created under the Information Technology Act, 2000 and its associated rules. It is generated by a computer system and does not require physical or digital signatures.</p>
                                    </li>
                                    <li>
                                        <p>This document is provided in compliance with Rule 3(1) of the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021.</p>
                                    </li>
                                    <li>
                                        <p>The Haatak Platform facilitates users to purchase/sell/transfer gold in digital form from a brand named &lsquo;Safe Gold&rsquo; operated and managed by Digital Gold India Private Limited.</p>
                                    </li>
                                    <li>
                                        <p>You understand that our company acts solely as a distributor facilitating the purchase of gold from SafeGold.</p>
                                    </li>
                                    <li>
                                        <p>We are not responsible for any issues or disputes related to the purchase of gold or services provided by SafeGold.</p>
                                    </li>
                                    <li>
                                        <p>You understand that SafeGold handles the purchase and sale of gold. Physical gold will be stored with Brinks India Private Limited (&ldquo;Custodian&rdquo;).</p>
                                    </li>
                                    <li>
                                        <p>To protect your interests, SafeGold has appointed a trustee (&ldquo;Trustee Administrator&rdquo;).</p>
                                    </li>
                                    <li>
                                        <p>Please read these terms carefully before using our platform. The company reserves the right to modify these terms at any time.</p>
                                    </li>
                                    <li>
                                        <p>Before using our services, we recommend reviewing the terms of service and privacy policy of Digital Gold India Private Limited.</p>
                                    </li>
                                    <li>
                                        <p>By using our services, you acknowledge that Haatak is not responsible for the quality of physical gold offered by Digital Gold India Private Limited.</p>
                                    </li>
                                </ol>
                            </div>

                            {/* Section 2: Definitions */}
                            <div className="  pl-4">
                                <h3 className={`${gilroy_semibold.className} text-lg md:text-xl text-[#2E0A49] mt-6 mb-2`}>
                                    2. Definitions
                                </h3>

                                <p>For the purpose of these Terms, the following definitions apply:</p>

                                <ul className="list-disc pl-5 space-y-2">
                                    <li><span className="font-semibold">Business Day:</span> A day when commercial banks in Bengaluru are open.</li>
                                    <li><span className="font-semibold">Customer:</span> Any individual who uses the platform to buy or sell precious metals.</li>
                                    <li><span className="font-semibold">Customer Account:</span> The account created by you.</li>
                                    <li><span className="font-semibold">Platform:</span> Our mobile application and website &ldquo;www.Haatak.com&rdquo;.</li>
                                    <li><span className="font-semibold">Precious Metal:</span> Physical gold, silver or other precious metals in bullion form.</li>
                                    <li><span className="font-semibold">Force Majeure Event:</span> Events beyond Haatak&rsquo;s control like natural disasters, strikes, war, etc.</li>
                                    <li><span className="font-semibold">Reward Program:</span> Programs offered to customers at Haatak&rsquo;s discretion.</li>
                                </ul>
                            </div>

                            {/* Section 3: Services */}
                            <div className="  pl-4">
                                <h3 className={`${gilroy_semibold.className} text-lg md:text-xl text-[#2E0A49] mt-6 mb-2`}>
                                    3. Terms and Conditions of Services
                                </h3>

                                <ul className="list-disc pl-5 space-y-2">
                                    <li>Unibridg Assets and Vault Private Limited sells Precious Metal and provides related services.</li>
                                    <li>Services are provided on an &ldquo;AS IS&rdquo; and &ldquo;AS AVAILABLE&rdquo; basis.</li>
                                    <li>Only natural persons above 18 years, Indian residents are eligible to participate in Reward Programs.</li>
                                    <li>Haatak reserves the right to start, pause, or discontinue any Reward Program.</li>
                                    <li>Customers must provide accurate KYC information when requested.</li>
                                    <li>Customers agree to indemnify Haatak against third-party claims.</li>
                                    <li>Except for proven fraud, customers release Haatak from liability related to Reward Programs.</li>
                                    <li>Haatak&rsquo;s decisions regarding Reward Programs are final and binding.</li>
                                </ul>
                            </div>

                            {/* Section 4: Trustee and Safekeeping */}
                            <div className="  pl-4">
                                <h3 className={`${gilroy_semibold.className} text-lg md:text-xl text-[#2E0A49] mt-6 mb-2`}>
                                    4. Trustee, Intermediaries, and Safe Keeping Arrangement
                                </h3>

                                <h4 className={`${gilroy_semibold.className} text-base md:text-lg text-[#2E0A49] mt-4 mb-2`}>
                                    4.1 Appointment of Intermediaries
                                </h4>
                                <p>Haatak may appoint intermediaries to assist in providing services.</p>

                                <h4 className={`${gilroy_semibold.className} text-base md:text-lg text-[#2E0A49] mt-4 mb-2`}>
                                    4.2 Appointment of Trustee Administrator
                                </h4>
                                <p>Customer Precious Metal will be monitored by the Trustee Administrator.</p>

                                <h4 className={`${gilroy_semibold.className} text-base md:text-lg text-[#2E0A49] mt-4 mb-2`}>
                                    4.3 Safe Keeping/Vaulting of Precious Metal
                                </h4>
                                <p>Customer Precious Metal purchased will be stored with a custodian in a vault.</p>
                            </div>

                            {/* Section 5: Storage */}
                            <div className="  pl-4">
                                <h3 className={`${gilroy_semibold.className} text-lg md:text-xl text-[#2E0A49] mt-6 mb-2`}>
                                    5. Storage of Precious Metal
                                </h3>

                                <ul className="list-disc pl-5 space-y-2">
                                    <li>Free storage for 5 years from the date of purchase.</li>
                                    <li>After free period, storage charges will apply.</li>
                                    <li>Customers must take delivery within the Maximum Storage Period.</li>
                                    <li>Valid address and documents required for delivery.</li>
                                    <li>If no valid address provided, Haatak will attempt to contact you.</li>
                                    <li>After Grace Period, unclaimed gold will be sold at prevailing market price.</li>
                                    <li>Sale proceeds will be held for 3 years before being transferred to relief funds.</li>
                                </ul>
                            </div>

                            {/* Section 6-8: Force Majeure, Termination */}
                            <div className="  pl-4">
                                <h3 className={`${gilroy_semibold.className} text-lg md:text-xl text-[#2E0A49] mt-6 mb-2`}>
                                    6. Force Majeure
                                </h3>
                                <p>Haatak is discharged from performance during events beyond its control.</p>

                                <h3 className={`${gilroy_semibold.className} text-lg md:text-xl text-[#2E0A49] mt-6 mb-2`}>
                                    7. Termination of Services
                                </h3>
                                <p>Haatak may modify, suspend, or terminate access at any time.</p>

                                <h3 className={`${gilroy_semibold.className} text-lg md:text-xl text-[#2E0A49] mt-6 mb-2`}>
                                    8. Consequences of Termination
                                </h3>
                                <p>Upon termination, the Trustee Administrator will handle customer precious metal holdings.</p>
                            </div>

                            {/* Section 9: Governing Law */}
                            <div className="  pl-4">
                                <h3 className={`${gilroy_semibold.className} text-lg md:text-xl text-[#2E0A49] mt-6 mb-2`}>
                                    9. Governing Law and Dispute Resolution
                                </h3>
                                <p>These Terms are governed by Indian law. Disputes will be settled through binding arbitration in Bengaluru.</p>
                            </div>

                            {/* Section 10-12: Account, Orders, Purchase */}
                            <div className="  pl-4">
                                <h3 className={`${gilroy_semibold.className} text-lg md:text-xl text-[#2E0A49] mt-6 mb-2`}>
                                    10. Creation of Customer Account
                                </h3>
                                <p>Customers must complete registration and provide accurate information.</p>

                                <h3 className={`${gilroy_semibold.className} text-lg md:text-xl text-[#2E0A49] mt-6 mb-2`}>
                                    11. Placing Customer Order
                                </h3>
                                <p>KYC documentation may be required before placing orders.</p>

                                <h3 className={`${gilroy_semibold.className} text-lg md:text-xl text-[#2E0A49] mt-6 mb-2`}>
                                    12. Purchase of Precious Metal
                                </h3>
                                <p>Minimum purchase of ₹1.00. Prices may vary and are subject to change.</p>
                            </div>

                            {/* Section 13-15: Delivery, Sale, Transfer */}
                            <div className="  pl-4">
                                <h3 className={`${gilroy_semibold.className} text-lg md:text-xl text-[#2E0A49] mt-6 mb-2`}>
                                    13. Delivery of Precious Metal
                                </h3>
                                <p>Delivery requests require payment of applicable charges. Delivery within 7 business days.</p>

                                <h3 className={`${gilroy_semibold.className} text-lg md:text-xl text-[#2E0A49] mt-6 mb-2`}>
                                    14. Sale of Customer Precious Metal
                                </h3>
                                <p>Sale requests will be processed within 2 business days. Payments to bank account.</p>

                                <h3 className={`${gilroy_semibold.className} text-lg md:text-xl text-[#2E0A49] mt-6 mb-2`}>
                                    15. Transfer of Precious Metal
                                </h3>
                                <p>Includes gifting, exchange for jewellery, and lease options.</p>
                            </div>

                            {/* Section 16-19: Fraud, Platform Use, Fees */}
                            <div className="  pl-4">
                                <h3 className={`${gilroy_semibold.className} text-lg md:text-xl text-[#2E0A49] mt-6 mb-2`}>
                                    16. Fraudulent Transactions
                                </h3>
                                <p>Customers must protect payment information. Haatak will assist with fraud cases.</p>

                                <h3 className={`${gilroy_semibold.className} text-lg md:text-xl text-[#2E0A49] mt-6 mb-2`}>
                                    17. Use of the Platform and Services
                                </h3>
                                <p>Services are for personal use. Haatak may experience service interruptions.</p>

                                <h3 className={`${gilroy_semibold.className} text-lg md:text-xl text-[#2E0A49] mt-6 mb-2`}>
                                    18. Suspension/Closure of Account
                                </h3>
                                <p>Accounts may be suspended for suspicious activity.</p>

                                <h3 className={`${gilroy_semibold.className} text-lg md:text-xl text-[#2E0A49] mt-6 mb-2`}>
                                    19. Fees
                                </h3>
                                <p>Customers are liable for all fees associated with platform use.</p>
                            </div>

                            {/* Section 20-33: Other Terms */}
                            <div className="  pl-4">
                                <h3 className={`${gilroy_semibold.className} text-lg md:text-xl text-[#2E0A49] mt-6 mb-2`}>
                                    20. Member Eligibility
                                </h3>
                                <p>Available only to persons who can enter legally binding contracts in India.</p>

                                <h3 className={`${gilroy_semibold.className} text-lg md:text-xl text-[#2E0A49] mt-6 mb-2`}>
                                    30. Disclaimer of Warranties
                                </h3>
                                <p>Haatak makes no representations or warranties about precious metal quality.</p>

                                <h3 className={`${gilroy_semibold.className} text-lg md:text-xl text-[#2E0A49] mt-6 mb-2`}>
                                    32. Limitation of Liability
                                </h3>
                                <p>Haatak not liable for special, consequential, or incidental damages.</p>

                                <h3 className={`${gilroy_semibold.className} text-lg md:text-xl text-[#2E0A49] mt-6 mb-2`}>
                                    33. Amendments, Acceptance of Terms
                                </h3>
                                <p>Haatak reserves the right to change terms at any time.</p>
                            </div>

                            {/* Section 34-37: Final Sections */}
                            <div className="  pl-4">
                                <h3 className={`${gilroy_semibold.className} text-lg md:text-xl text-[#2E0A49] mt-6 mb-2`}>
                                    36. Grievance Redressal
                                </h3>
                                <p>
                                    <span className="font-semibold">Grievance Officer:</span> Mr. Venkatesh L<br />
                                    <span className="font-semibold">Email:</span> venkatesh@haatak.com<br />
                                    <span className="font-semibold">Phone:</span> 99000 18989
                                </p>

                                <h3 className={`${gilroy_semibold.className} text-lg md:text-xl text-[#2E0A49] mt-6 mb-2`}>
                                    Contact Us
                                </h3>
                                <address className="not-italic mt-3">
                                    Unibridg Assets and Vault Private Limited.<br />
                                    Haatak<br />
                                    455 D, 1st Floor, Eshaan Arcade<br />
                                    REMCO BHEL Layout, Rajarajeshwari Nagar<br />
                                    Bengaluru - 560098
                                </address>

                                <h3 className={`${gilroy_semibold.className} text-lg md:text-xl text-[#2E0A49] mt-6 mb-2`}>
                                    Policy Changes
                                </h3>
                                <p>
                                    Haatak reserves the right to amend these terms at any time without prior notice. Changes will be posted on our website, and it is the customer&rsquo;s responsibility to review the policy regularly.
                                </p>

                                <p className="mt-8 italic">
                                    Thank you for trusting Haatak with your information.
                                </p>
                            </div>
                        </div>
                    </section>
                </article>
            </div>
        </div>
    )
}

export default TermsConditionsPage;